# Generated by Django 3.2.8 on 2021-10-07 14:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_xid', models.CharField(max_length=126)),
                ('token', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=True)),
                ('enable_at', models.DateTimeField()),
                ('balance', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw')], max_length=1)),
                ('amount', models.FloatField(default=0)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.CharField(max_length=126)),
                ('customer_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.customerwallet')),
            ],
        ),
    ]
