# Generated by Django 3.2.8 on 2021-10-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerwallet',
            name='disable_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customerwallet',
            name='enable_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='customerwallet',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
