# Generated by Django 3.2.8 on 2021-10-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20211008_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(max_length=126, unique=True),
        ),
    ]
